# =============================================================================
# Variables — matches terraform.tfvars.json generated by bootstrap automation
# =============================================================================

variable "site_name" {
  description = "Short site identifier (e.g., sbom, pf-billing-sales)"
  type        = string
}

variable "mi_client_id" {
  description = "Client ID of this site's dedicated managed identity for OIDC auth"
  type        = string
}

variable "custom_domain" {
  description = "Full custom domain (e.g., sbom.internal.veradigm.com)"
  type        = string
}

variable "regions" {
  description = "Primary and DR region configuration"
  type = object({
    primary = string
    dr      = string
  })
  default = {
    primary = "eastus2"
    dr      = "centralus"
  }
}

variable "resource_group" {
  description = "Resource group for SWA instances. Per-site (rg-staticweb-<site>-prd), set by bootstrap in terraform.tfvars.json — no default so a missing value fails Terraform plan loudly."
  type        = string
}

variable "swa_name_primary" {
  description = "SWA instance name for primary region (e.g., swa-sbom-ue2)"
  type        = string
}

variable "swa_name_dr" {
  description = "SWA instance name for DR region (e.g., swa-sbom-uc1)"
  type        = string
}

variable "tags" {
  description = "Resource tags applied to all resources"
  type        = map(string)
  default     = {}
}

# ── Entra ID (AAD) SSO ──
# Shared app registration for all static web sites (app-staticweb-sso).
# forwardingGateway in staticwebapp.config.json handles auth redirects via Front Door.
# SWA Standard tier is required for forwardingGateway to function.

variable "aad_client_id" {
  description = "Client ID of the shared Entra app registration (app-staticweb-sso)"
  type        = string
  sensitive   = true
}

variable "aad_client_secret" {
  description = "Client secret for the shared Entra app registration"
  type        = string
  sensitive   = true
}

# ── Function App backend (/api/*) ──
# The Automation Hub backend is a stateless proxy to GitHub / Jira / Xray. These
# values are stored as Key Vault secrets (keyvault.tf) and referenced by the
# Function App via @Microsoft.KeyVault(...). Passed in as TF_VAR_* from GitHub
# repo secrets in deploy-infra.yml. Defaults keep `terraform plan` working on PRs
# (where the secrets are not injected) — real values are only needed on apply.

variable "github_token" {
  description = "GitHub PAT used by the backend for Copilot/Models + repo dispatch + artifact download (GITHUB_COPILOT_TOKEN/GITHUB_TOKEN)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "github_owner" {
  description = "GitHub org/owner of the test-automation repo the backend dispatches to"
  type        = string
  default     = "techops"
}

variable "github_repo" {
  description = "GitHub repo the backend dispatches workflows to / commits features to"
  type        = string
  default     = "az-staticWeb-automation-pw"
}

variable "github_target_branch" {
  description = "Branch the backend commits generated feature files to. Default main (legacy); set to a non-default branch to keep authenticated users from writing straight to main."
  type        = string
  default     = "main"
}

variable "jira_user" {
  description = "Jira account email for Basic auth (JIRA_USER)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "jira_api_token" {
  description = "Jira API token (JIRA_API_TOKEN)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "jira_base_url" {
  description = "Jira base URL"
  type        = string
  default     = "https://automationhubpw.atlassian.net"
}

variable "xray_client_id" {
  description = "Xray Cloud client id (XRAY_CLIENT_ID)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "xray_client_secret" {
  description = "Xray Cloud client secret (XRAY_CLIENT_SECRET)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "function_runtime_version" {
  description = "Node.js runtime version for the Function App"
  type        = string
  default     = "20"
}

# ── Optional overrides ──

variable "action_group_id" {
  description = "Resource ID of the shared Action Group for alert routing"
  type        = string
  default     = "/subscriptions/PLACEHOLDER/resourceGroups/PLACEHOLDER/providers/Microsoft.Insights/actionGroups/PLACEHOLDER"
}

variable "availability_test_locations" {
  description = "Azure regions for Application Insights availability tests"
  type        = list(string)
  default = [
    "us-va-ash-azr", # East US (Virginia)
    "us-ca-sjc-azr", # West US (California)
    "us-il-ch1-azr", # North Central US (Chicago)
    "us-tx-sn1-azr", # South Central US (San Antonio)
    "us-fl-mia-edge" # Central US (Miami)
  ]
}
