# =============================================================================
# Variables — matches terraform.tfvars.json generated by bootstrap automation
# =============================================================================

variable "site_name" {
  description = "Short site identifier (e.g., sbom, pf-billing-sales)"
  type        = string
}

variable "mi_client_id" {
  description = "Client ID of this site's dedicated managed identity for OIDC auth"
  type        = string
}

variable "custom_domain" {
  description = "Full custom domain (e.g., sbom.internal.veradigm.com)"
  type        = string
}

variable "regions" {
  description = "Primary and DR region configuration"
  type = object({
    primary = string
    dr      = string
  })
  default = {
    primary = "eastus2"
    dr      = "centralus"
  }
}

variable "resource_group" {
  description = "Resource group for SWA instances. Per-site (rg-staticweb-<site>-prd), set by bootstrap in terraform.tfvars.json — no default so a missing value fails Terraform plan loudly."
  type        = string
}

variable "frontdoor_resource_group" {
  description = "Resource group containing the shared Front Door profile (Neon subscription)"
  type        = string
}

variable "frontdoor_profile_name" {
  description = "Name of the shared Front Door Premium profile (Neon subscription)"
  type        = string
}


variable "dns_zone_name" {
  description = "Azure DNS zone for custom domains"
  type        = string
  default     = "internal.veradigm.com"
}

variable "dns_zone_resource_group" {
  description = "Resource group containing the DNS zone"
  type        = string
  default     = "Ue1NePrdPublicDNS-RG"
}

variable "swa_name_primary" {
  description = "SWA instance name for primary region (e.g., swa-sbom-ue2)"
  type        = string
}

variable "swa_name_dr" {
  description = "SWA instance name for DR region (e.g., swa-sbom-uc1)"
  type        = string
}

variable "tags" {
  description = "Resource tags applied to all resources"
  type        = map(string)
  default     = {}
}

# ── Entra ID (AAD) SSO ──
# Shared app registration for all static web sites (app-staticweb-sso).
# forwardingGateway in staticwebapp.config.json handles auth redirects via Front Door.
# SWA Standard tier is required for forwardingGateway to function.

variable "aad_client_id" {
  description = "Client ID of the shared Entra app registration (app-staticweb-sso)"
  type        = string
  sensitive   = true
}

variable "aad_client_secret" {
  description = "Client secret for the shared Entra app registration"
  type        = string
  sensitive   = true
}

# ── Optional overrides ──

variable "log_analytics_workspace_id" {
  description = "Resource ID of the central Log Analytics workspace for Application Insights"
  type        = string
  default     = "/subscriptions/54305029-7d35-40a9-8bf9-950963b449cc/resourceGroups/ue1neprdresourcegroup/providers/Microsoft.OperationalInsights/workspaces/neon-log-analytics-workspace"
}

variable "action_group_id" {
  description = "Resource ID of the shared Action Group for alert routing"
  type        = string
  default     = "/subscriptions/PLACEHOLDER/resourceGroups/PLACEHOLDER/providers/Microsoft.Insights/actionGroups/PLACEHOLDER"
}

variable "availability_test_locations" {
  description = "Azure regions for Application Insights availability tests"
  type        = list(string)
  default = [
    "us-va-ash-azr", # East US (Virginia)
    "us-ca-sjc-azr", # West US (California)
    "us-il-ch1-azr", # North Central US (Chicago)
    "us-tx-sn1-azr", # South Central US (San Antonio)
    "us-fl-mia-edge" # Central US (Miami)
  ]
}
